[versions]
app = "2.1.0"
java = "25"

[libraries]
#########################################
# spring boot
#########################################
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }

#########################################
# unit test library
#########################################
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
jsoup = { module = "org.jsoup:jsoup", version = { strictly = "1.21.2" } }

#########################################
# gradle plugins
#########################################
spring-boot = { module = "org.springframework.boot:org.springframework.boot.gradle.plugin", version = { strictly = "4.0.1" } }
spring-dependency-management = { module = "io.spring.dependency-management:io.spring.dependency-management.gradle.plugin", version = { strictly = "1.1.7" }  }
sonatype-central-upload = { module = "cl.franciscosolis.sonatype-central-upload:cl.franciscosolis.sonatype-central-upload.gradle.plugin", version = { strictly = "1.0.3" } }
spotless = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version = { strictly = "8.1.0" } }
