[versions]
app = "2.0.0"
java = "25"

[plugins]
spring-boot = { id = "org.springframework.boot", version = { strictly = "4.0.0" } }
spring-dependency-management = { id = "io.spring.dependency-management", version = { strictly = "1.1.7" }  }
spotless = { id = "com.diffplug.spotless", version = { strictly = "8.1.0" } }

[libraries]
#########################################
# spring boot
#########################################
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }

#########################################
# unit test library
#########################################
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

#########################################
# gradle plugins
#########################################
sonatype-central-upload = { module = "cl.franciscosolis.sonatype-central-upload:cl.franciscosolis.sonatype-central-upload.gradle.plugin", version = { strictly = "1.0.3" } }
