[versions]
app = "1.0.4"
java = "21"

[plugins]
spring-boot = { id = "org.springframework.boot", version = { strictly = "3.5.8" } }
spring-dependency-management = { id = "io.spring.dependency-management", version = { strictly = "1.1.7" }  }
sonatype-central-upload = { id = "cl.franciscosolis.sonatype-central-upload", version = { strictly = "1.0.3" } }
spotless = { id = "com.diffplug.spotless", version = { strictly = "8.1.0" } }

[libraries]
#########################################
# spring boot
#########################################
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }

spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

#########################################
# unit test library
#########################################
rest-assured = { module = "io.rest-assured:rest-assured", version = { strictly = "5.5.6" } }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
