feature-flags:
  path-patterns:
    includes:
      - "/**"
  feature-names:
    experimental-stage-endpoint: true
    development-stage-endpoint: false
    enable-class-level-feature: true
    disable-class-level-feature: false
    legacy-api: false
    special-endpoint: true
  response:
    type: json
